# Deploy bundled JS and README.md to gh-pages branch
name: Deploy to gh-pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: latest

      - name: Build JS files
        run: deno task build

      - name: Prepare deployment folder
        run: |
          mkdir deploy
          cp README.md deploy/
          cp dist/*.js deploy/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: true
  
